version: '3.5'

services:
  api:
    container_name: users-crud_api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes: 
      - .:/home/api
      - /home/api/node_modules
    environment:
      DOCKER_DB_HOST: database
      POSTGRES_PORT: 5432

  database:
    container_name: users-crud_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - ${POSTGRES_PORT}:5432
